apiVersion: v1
kind: Service
metadata:
  name: pitstop-webapp
  namespace: pitstop
spec:
  selector:
    app: pitstop-webapp
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30082
