apiVersion: v1
kind: Service
metadata:
  name: pitstop-vehicle
  namespace: pitstop
spec:
  selector:
    app: pitstop-vehicle
  type: NodePort
  ports:
    - port: 80
      targetPort: 3002
      nodePort: 30091
