apiVersion: v1
kind: Service
metadata:
  name: pitstop-express-gateway
  namespace: pitstop
spec:
  selector:
    app: pitstop-express-gateway
  type: NodePort
  ports:
    - port: 80
      targetPort: 3003
      nodePort: 30083
