name: CI Cleanup

on:
  workflow_run:
    workflows: ["CI-Sec Frontend"]
    types:
      - completed

jobs:
  cleanup:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Cleanup Success Message
        run: echo "✅ Cleanup job executed successfully after CI-Sec Frontend completed!"
