name: CI-Sec Frontend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # ───────────────────────────── prepare ─────────────────────────────
  prepare:
    runs-on: [self-hosted, docker]              # ton runner
    defaults:
      run:
        working-directory: pitstop-webapp       # dossier du micro-service

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4             # installe Node
        with:
          node-version: 18
          cache: 'npm'

      - name: Install deps
        run: npm ci

  # ───────────────────────────── SAST (Sonar + Semgrep) ───────────────
  sast:
    needs: prepare
    runs-on: [self-hosted, docker]
    if: github.event_name == 'pull_request'     # scanne seulement les PR
    defaults:
      run:
        working-directory: pitstop-webapp

    steps:
      - uses: actions/checkout@v4

      # -------- Sonar --------
      - name: Sonar Scan
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=pitstop-webapp-hicham
            -Dsonar.organization=hichamben

      # -------- Semgrep --------
      - name: Semgrep Scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/react                    # règles React
          generateSarif: true

      # -------- Bloquer si sévérité >= 5 --------
      - name: Fail if CVSS >=5
        run: |
          n=$(jq '.runs[].results
                  | map(select(.properties.security_severity_level
                               | tonumber >= 5)) | length' semgrep.sarif || echo 0)
          if [ "$n" -gt 0 ]; then
            echo "::error::Critical SAST finding (CVSS >=5)."
            exit 1
          fi
