name: CI – Webapp (build & push)

on:
  push:
    branches: [main]
    paths:
      - 'pitstop-webapp/**'
  pull_request:
    paths:
      - 'pitstop-webapp/**'

jobs:
  build-and-push:
    runs-on: [self-hosted, docker]       # 1️⃣

    defaults:                           # 2️⃣
      run:
        working-directory: pitstop-webapp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .                    # 3️⃣
          push: true
          tags: hichamben21/webapp:latest
