apiVersion: v1
kind: Service
metadata:
  name: pitstop-workshop
  namespace: pitstop
spec:
  selector:
    app: pitstop-workshop
  type: NodePort
  ports:
    - port: 80
      targetPort: 3004
      nodePort: 30084
